// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-1nb8CZwiaMZw8zmMLp51v_vhz94sW7Q',
    appId: '1:900791277185:web:10abb8c19a76712bf7df80',
    messagingSenderId: '900791277185',
    projectId: 'ncc-apps-47109',
    authDomain: 'ncc-apps-47109.firebaseapp.com',
    databaseURL: 'https://ncc-apps-47109-default-rtdb.firebaseio.com',
    storageBucket: 'ncc-apps-47109.appspot.com',
    measurementId: 'G-CZ94N4SZ0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk1hVHoQ0UGIvRmxK7DtfWesiSRlxbL20',
    appId: '1:900791277185:android:7e5afe8c126936bbf7df80',
    messagingSenderId: '900791277185',
    projectId: 'ncc-apps-47109',
    databaseURL: 'https://ncc-apps-47109-default-rtdb.firebaseio.com',
    storageBucket: 'ncc-apps-47109.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9OguUHp3szFP2uVCNXP76ixMDOk8qj10',
    appId: '1:900791277185:ios:a8cb7231f4f7a966f7df80',
    messagingSenderId: '900791277185',
    projectId: 'ncc-apps-47109',
    databaseURL: 'https://ncc-apps-47109-default-rtdb.firebaseio.com',
    storageBucket: 'ncc-apps-47109.appspot.com',
    androidClientId: '900791277185-97sbjkqlbpatrgen755j4235gc8l37o4.apps.googleusercontent.com',
    iosClientId: '900791277185-4324gl31t09cijvq1g190685cvhfqb62.apps.googleusercontent.com',
    iosBundleId: 'com.example.nccApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9OguUHp3szFP2uVCNXP76ixMDOk8qj10',
    appId: '1:900791277185:ios:2f1521b7dff6e1a4f7df80',
    messagingSenderId: '900791277185',
    projectId: 'ncc-apps-47109',
    databaseURL: 'https://ncc-apps-47109-default-rtdb.firebaseio.com',
    storageBucket: 'ncc-apps-47109.appspot.com',
    androidClientId: '900791277185-97sbjkqlbpatrgen755j4235gc8l37o4.apps.googleusercontent.com',
    iosClientId: '900791277185-sgqk9lh9qlonicc1fcus9ioi7o5amkf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.nccApps.RunnerTests',
  );
}
